;;; MyInit --- A decent Emacs config for devs in a VS Code era...
;;;
;;; This Emacs configuration was generated by My Machine Life
;;;
;;; Commentary:
;;;
;;; This is my personal config worked over with some effort.  The configuration
;;; is expected to work both with Emacs opened as a windowed application or
;;; opened in a terminal `-nw'.
;;;
;;; Code:
;;;

;;
;;; Package management
;;

(defun my/setup-package-el ()
  "Load and configure `package.el' for melpa and org repositories."
  ;; Load package.el so we can configure it.
  (require 'package)

  ;; Update package sources to include Melpa and Org package repositories
  (setq package-archives '(("elpa" . "https://elpa.gnu.org/packages/")
                           ("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")))

  ;; Initialize packages for Emacs versions under 27 since they are initialized
  ;; automatically as of version 27
  (when (< emacs-major-version 27)
    (package-initialize))

  ;; Fetched the latest packages if that has not been done before
  (unless package-archive-contents
    (package-refresh-contents)))

(defun my/setup-use-package ()
  "Install and configure `use-package' for loading and configuring packages."

  ;; Install `use-package' for installing packages in a declarative way
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  ;; Require `use-package' immediately since we use it later to install
  ;; packages
  (require 'use-package)

  ;; Configure `use-package' to always ensure successful setup by default
  (setq use-package-always-ensure t)

  (message "Setup use-package"))

(defun my/set-sane-defaults ()
  "Setup sane defaults for a /modern/-looking Emacs."
  (interactive)

  ;; Remove the default Emacs splash screen on startup
  (setq inhibit-startup-message t)

  ;; Increase the default buffer padding a little
  (set-fringe-mode 10)

  ;; Remove the menu bar (e.g.: `File', `Edit', etc.) as we have key bindings
  ;; for everything we need
  (menu-bar-mode -1)

  ;; Disable the computer beep from Emacs in favor of a visual flash instead
  (setq visible-bell t)

  ;; Use a vertical bar `|' as a cursor
  (setq-default cursor-type 'bar))

;; Custom function to setup GUI Emacs settings
(defun my/configure-graphic-display ()
  "Configure Emacs to run with graphic settings."
  (interactive)

  ;; Set the selected frame to fullscreen.
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  ;; Set frames to be fullscreen by default.
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable various GUI features we don't need since we're relying on bindings.
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (tooltip-mode -1)

  ;; Add a little breathing room between lines for most full-height fonts.
  (setq-default line-spacing 0.2)
  t)

;; Custom function to setup terminal Emacs settings
(defun my/configure-tty-display ()
  "Configure Emacs to run with TTY display settings."
  (interactive)

  ;; If the frame is viewed in a terminal, enable XTerm mouse capabilities such
  ;; as scrolling, clicking, etc.  It's note strictly necessary but is very
  ;; convenient when still unfamiliar with many key bindings.
  (xterm-mouse-mode 1)
  t)

(message "Goliath online!")

(provide 'my-emacs-config)
;;; my-emacs-config.el ends here
