# https://starship.rs/config/

# To install this configuration file locally:
#
# ```sh
# ln -s $PWD/starship.toml ~/.config/starship.toml
# ```

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# The name of the module we are configuring is "character"
[character]

# Replace the "❯" symbol in the prompt with "➜"
success_symbol = "[➜](bold green)"
